# -*- coding: utf-8 -*-
"""P1_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kB3AlQuknS19ul9Bfzazb4x5E_kP5u1y
"""

n = input()
a = input().split()
b = input().split()
x1 = int(a[0])
y1 = int(a[1])
x2 = int(b[0])
y2 = int(b[1])
if checkerboard[x1][y1]==0 :
    print("No")
else :
    if n=="國王" :
        if abs(x2-x1)<2 and abs(y2-y1)<2 and checkerboard[x2][y2]==0 :
            print("Yes")
        else :
            print("No")
    elif n=="皇后" :
        if x1==x2 and y1==y2 :
            print("No")
        else :
            if (x1==x2 or y1==y2 or abs(x2-x1)==abs(y2-y1)) and checkerboard[x2][y2]==0 :
                if x1==x2 :
                    ax=0
                else :
                    ax=(x2-x1)//abs(x2-x1)
                if y1==y2 :
                    ay=0
                else :
                    ay=(y2-y1)//abs(y2-y1)
                tx=x1+ax
                ty=y1+ay
                while tx!=x2 or ty!=y2 :
                    if checkerboard[tx][ty]==1 :
                        break
                    else :
                        tx=tx+ax
                        ty=ty+ay
                if tx==x2 and ty==y2 :
                    print("Yes")
                else :
                    print("No")
            else :
                print("No")
    elif n=="主教" :
        if x1==x2 and y1==y2 :
            print("No")
        else :
            if (abs(x2-x1)==abs(y2-y1)) and checkerboard[x2][y2]==0 :
                ax=(x2-x1)//abs(x2-x1)
                ay=(y2-y1)//abs(y2-y1)
                tx=x1+ax
                ty=y1+ay
                while tx!=x2 or ty!=y2 :
                    if checkerboard[tx][ty]==1 :
                        break
                    else :
                        tx=tx+ax
                        ty=ty+ay
                if tx==x2 and ty==y2 :
                    print("Yes")
                else :
                    print("No")
            else :
                print("No")
    elif n=="城堡" :
        if x1==x2 and y1==y2 :
            print("No")
        else :
            if (x1==x2 or y1==y2) and checkerboard[x2][y2]==0 :
                if x1==x2 :
                    ax=0
                else :
                    ax=(x2-x1)//abs(x2-x1)
                if y1==y2 :
                    ay=0
                else :
                    ay=(y2-y1)//abs(y2-y1)
                tx=x1+ax
                ty=y1+ay
                while tx!=x2 or ty!=y2 :
                    if checkerboard[tx][ty]==1 :
                        break
                    else :
                        tx=tx+ax
                        ty=ty+ay
                if tx==x2 and ty==y2 :
                    print("Yes")
                else :
                    print("No")
            else :
                print("No")
    elif n=="騎士" :
        if (abs(y2-y1)==2 and abs(x2-x1)==1 or abs(x2-x1)==2 and abs(y2-y1)==1) and checkerboard[x2][y2]==0 :
            print("Yes")
        else :
            print("No")
    elif n=="士兵" :
        if y1==y2 and x2==x1+1 and checkerboard[x2][y2]==0 :
            print("Yes")
        else :
            print("No")